#!/bin/bash

cat ~/.config/i3/*.conf > ~/.config/i3/config

sudo curl -L https://raw.githubusercontent.com/Vorago/i3exit/master/i3exit -o /usr/local/bin/i3exit
sudo chmod +x /usr/local/bin/i3exit

sudo curl -L https://github.com/Vorago/open-ide/releases/download/v1.0.0/open-ide -o /usr/local/bin/open-ide
sudo chmod +x /usr/local/bin/open-ide



# critical
sudo pacman -Syu
sudo pacman -Sy yay vim
yay -Sy rofi

# shell
sudo pacman -S zsh starship fzf
yay -S oh-my-zsh-git oh-my-zsh-plugin-autosuggestions

# other
sudo pacman -Sy xclip unzip xdotool telegram-desktop flameshot picom docker docker-compose i3status-rust bitwarden direnv
yay -Sy dropbox insync jetbrains-toolbox google-chrome i3lock-fancy-rapid-git nvm slack-desktop thefuck joplin-appimage nerd-fonts-terminus nerd-fonts-hack-complete-git otf-nerd-fonts-fira-code


echo "change shell"
echo "chsh -s $(which zsh)"
