#!/bin/bash

cat ~/.config/i3/*.conf > ~/.config/i3/config

sudo curl https://raw.githubusercontent.com/Vorago/i3exit/master/i3exit -o /usr/local/bin/i3exit
sudo chmod +x /usr/local/bin/i3exit

sudo curl https://github.com/Vorago/open-ide/releases/download/v1.0.0/open-ide -o /usr/local/bin/open-ide
sudo chmod +x /usr/local/bin/open-ide
