# https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "

[[block]]
block = "backlight"
minimum = 15
maximum = 100
cycle = [0, 50, 100]

[[block]]
block = "sound"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d/%m %R')"
